Repository DeveloperAcademy-POSTECH/MC2-Team4-Techome, pull requests merged in 2022-06, with the labels that each got.

#34 Feature/search bar ni
  Techome/Techome.xcodeproj/project.pbxproj
  Techome/Techome/Global/Extension/UIApplication+.swift
  Techome/Techome/ViewModel/SearchCaffeineStateHolder.swift
  Techome/Techome/Views/AddCaffeine/HomeView.swift
  Techome/Techome/Views/AddCaffeine/SearchBarView.swift
  Techome/Techome/Views/AddCaffeine/SearchCaffeineLayoutValue.swift
  Techome/Techome/Views/AddCaffeine/SearchCaffeineView.swift
  Techome/Techome/Views/AddCaffeine/SearchResultView.swift
Labels: 🛠 Feature

#37 Feature/trend t
  Techome/Techome.xcodeproj/project.pbxproj
  Techome/Techome/Views/Trend/ChartSelectionIndicatorView.swift
  Techome/Techome/Views/Trend/TrendChartView.swift
  Techome/Techome/Views/Trend/TrendView.swift
Labels: 🛠 Feature

#53 Feature/notification n
  Techome/Techome.xcodeproj/project.pbxproj
  Techome/Techome/Global/Manager/NotificationManager.swift
  Techome/Techome/Model/Notification/Notification.swift
  Techome/Techome/ViewModel/NotificationStateHolder.swift
  Techome/Techome/Views/Setting/NotificationView.swift
  Techome/Techome/Views/Setting/SettingView.swift
Labels: 🛠 Feature

#57 Feature/trend t
  Techome/Techome.xcodeproj/project.pbxproj
  Techome/Techome/ViewModel/TrendStateHolder.swift
  Techome/Techome/Views/Trend/TrendChartView.swift
  Techome/Techome/Views/Trend/TrendView.swift
Labels: 🛠 Feature

#58 Feature/settings g
  Techome/Techome.xcodeproj/project.pbxproj
  Techome/Techome/Views/Settings/SettingsMailView.swift
  Techome/Techome/Views/Settings/SettingsOpenSourceView.swift
  Techome/Techome/Views/Settings/SettingsPolicyView.swift
  Techome/Techome/Views/Settings/SettingsTeamView.swift
  Techome/Techome/Views/Settings/SettingsView.swift
Labels: 🌻 UI, 🛠 Feature

#60 Feature/settings g
  Techome/Techome/Global/Manager/BeverageManager.swift
  Techome/Techome/Views/Settings/SettingsOpenSourceView.swift
  Techome/Techome/Views/Settings/SettingsPolicyView.swift
  Techome/Techome/Views/Settings/SettingsTeamView.swift
  Techome/Techome/Views/Settings/SettingsView.swift
Labels: 🛠 Feature

#69 Feature/total list refactor logic m
  Techome/Techome/ViewModel/TotalListStateHolder.swift
  Techome/Techome/Views/MainView.swift
  Techome/Techome/Views/Today/TodayView.swift
  Techome/Techome/Views/TotalList/TotalListView.swift
  Techome/Techome/Views/Trend/TrendView.swift
Labels: 🛠 Feature

#62 [feat] 알림 기능 세팅창과 연결
  Techome/Techome.xcodeproj/project.pbxproj
  Techome/Techome/Views/Setting/NotificationView.swift
  Techome/Techome/Views/Setting/SettingView.swift
  Techome/Techome/Views/Settings/SettingsView.swift
Labels: 🛠 Feature

#79 Feature/add caffein view n
  Techome/Techome/Resources/EdiyaCoffeeData.json
  Techome/Techome/Views/AddCaffeine/SearchBarView.swift
  Techome/Techome/Views/AddCaffeine/SearchCaffeineView.swift
Labels: 🌻 UI
